### PR TITLE
Move Unlocked stage to Prevention

### LINKED ISSUE #174: Move the Unlocked stage activity to prevention
## Description
As a [USER],
I need see the current Unlocked stage under prevension,
so that I can use the activity as a prevention activity.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Locked stage moved under prevention. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by lunayach**
### Description
Moved Unlocked stage to Prevention and removed Peace Corps Policy Stage.
Fixes #174

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
All existing tests passed.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Raxerz** [comment]
@lunayach fix the conflict

**Comment by lunayach** [comment]
Addressed the comments.

**Comment by shreyans29** [comment]
@lunayach Solve the merge conflicts ..

**Comment by lunayach** [comment]
@shreyans29 resolved the merge conflicts.

**Pull request merged**
