### PR TITLE
Age gender intelligence [Not completely tested]

### LINKED ISSUE #169: The Chatbot has to store answers to questions in Memory
## Description
As a USER,
I need the Malaria Chatbot to remember answers to some questions like age and gender,
so that I do not have to answer repetitive questions again and again.

### Update [Required]
- [ ] The Malaria Chatbot should not ask same questions again, rather store the input and use it.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2  mentor.

## Estimation
5 hours

### PR DESCRIPTION
**Pull request by lunayach**
### Description
Added the **approach** for not asking age/gender again and storing in the memory. However. would require little more tweaks and training. 

Fixes #169

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Buddhiprabha** [comment]
@lunayach since this does not come under GSoC, can you please send this to the develop branch? @shreyans29 @Raxerz @paavininanda please suggest if there is an alternative.

**Comment by lunayach** [comment]
@Buddhiprabha @paavininanda @Raxerz @shreyans29 should I close this for now and later send PR to develop branch?

**Comment by Buddhiprabha** [comment]
Yes, please do so **after** GSoC branch is merged to develop @lunayach

**Comment by lunayach** [comment]
Okay @Buddhiprabha. Closing it for now.

**Pull request closed without merging**
