### PR TITLE
GSoC 2018 work

### PR DESCRIPTION
**Pull request by shreyans29**
### Description
This PR includes the work done in GSoC 2018

Fixes # [ISSUE]
GSoC 2017 code with 
#121 #122 #123 #124 #125 #126 #127 #128 #129 #130 #131 #132 #133 #134 #135 #136 #137 #138 #139 #152 #156 #159 #160 #163 #168

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Unit tests for both back end and angular code.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by paavininanda — APPROVED** [review]

**Comment by Raxerz** [comment]
Shouldn't this be gsoc18 to develop and then from develop to master?

**Comment by lunayach** [comment]
@Raxerz @shreyans29 @paavininanda @Buddhiprabha  there is a very minor change required. Instead of **1**, I need to have **level** in one statement in _app.routing.ts_. I guess, I somehow missed it while moving it to the prevention stage. Should I send a PR for this fix(Is it allowed after GSoC?)

**Comment by Buddhiprabha** [comment]
@Raxerz will the issue be solved when @lunayach's change is added? If yes, @lunayach should create an issue and send a PR to **develop** branch to fix it. Is it possible to add that PR to this PR then @Raxerz ?

**Comment by Raxerz** [comment]
@Buddhiprabha I made the change that @lunayach is referring to and it works fine.
Wouldn't it be better if he raises a PR to gsoc18 and once it is merged, it will get reflected in this PR as well?
The other way to go about it is that he raises a PR to develop branch and merging that first before we merge this so that the change gets reflected in this PR.

**Also, @lunayach reduce the spray by 0.25 and not by 1, it reduces pretty quickly right now**

**Comment by Buddhiprabha** [comment]
@Raxerz Okay,  let's merge this PR and then @lunayach can raise an issue and fix in **develop**. It is okay if it's not reflected in this PR.

**Review by Raxerz — APPROVED** [review]

**Comment by Raxerz** [comment]
@Buddhiprabha Shall I merge this? Needed your confirmation before merging since this is going into master

**Comment by Buddhiprabha** [comment]
@Raxerz yes, please do.

**Pull request merged**
