### PR TITLE
Added Malaria Dialogue Corpus

### LINKED ISSUE #159: Maintain Malaria Chatbot Corpus
## Description
As a developer,
I need to maintain a file with intents and corresponding sentences,
so that I can contributors can add sentences to the file, which can be used to train the chatbot.

### Update [Required]
- [ ] New file in the repository with Intents and sentences.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by lunayach**
### Description
Added Malaria Dialogue Corpus in the repo in word format.
Fixes #159 

### Type of Change:

- Outreach
- Documentation

### How Has This Been Tested?
N.A.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by lunayach** [comment]
Ya! @shreyans29 that is already the case i.e we have them in .md file.  But @Buddhiprabha suggested me to have this kind of document as well.

**Comment by Raxerz** [comment]
@Buddhiprabha what do you suggest?

**Comment by paavininanda** [comment]
I think we can merge this after @Raxerz approves.

**Comment by shreyans29** [comment]
So we will be having both this document and the .md file , @Raxerz  @paavininanda  @Buddhiprabha  ?

**Comment by paavininanda** [comment]
@shreyans29 As @Buddhiprabha suggested, I think we'll have both.

**Comment by Raxerz** [comment]
@shreyans29 @paavininanda @Buddhiprabha are we going to have the MD file and if we are should it be added to this PR or should we create a new issue for that?

**Pull request merged**
